* 100 Notable Books of 2020,

My quick selections.  Put the preferred on my list to read. The top
routine should get moved up

* fiction

** preferred (2)
***  The Memory Monster

By Yishai Sarid. Translated by Yardenne Greenspan. $20.00. Restless Books.

This brilliant short novel serves as a brave, sharp-toothed brief
against letting the past devour the present. Sarid tells the story of
a tour guide to the Nazi death camps and how his mind begins to slowly
unravel as his knowledge of the mechanics of genocide becomes an
obsession.

***  The Mirror & the Light

By Hilary Mantel. $30.00. Holt.

The final novel in Mantel’s “Wolf Hall” trilogy returns to the terror
of Henry VIII’s court, where falls from grace are sudden and
frequently fatal. For all its political and literary plotting, the
book is most memorable for its portraiture, with Henry’s secretary,
Thomas Cromwell, as our master painter.


** routine (7)

***  Hamnet

By Maggie O'Farrell. $26.95. Knopf.

Shakespeare’s son, Hamnet, died at 11, a few years before the
playwright wrote “Hamlet.” O’Farrell’s wondrous new novel is at once
an unsparingly eloquent record of love and grief and a vivid imagining
of how a child’s death was transfigured into art.

***  Beheld
By TaraShea Nesbit. $26.00. Bloomsbury.

In this plain-spoken and lovingly detailed historical novel, the story
of the Mayflower Pilgrims and Plymouth Colony is refracted through the
prism of female characters. Despite the novel’s quietness of telling,
its currency is the human capacity for cruelty and subjugation, of
pretty much everyone by pretty much everyone.

***  Deacon King Kong   

By James McBride. $28.00. Riverhead. 

At the center of this raucous novel by the National Book Award-winning
author of “The Good Lord Bird” are a hard-drinking church deacon and a
sudden, inexplicable act of violence. But that’s just one strand of
McBride’s tour de force, a book resounding with madcap characters and
sly commentary on race, crime and inequality.

***  Hurricane Season

By Fernanda Melchor. 
Translated by Sophie Hughes. $22.95. New Directions.  

This searing novel, the first in English by the Mexican Melchor,
dazzles with fury and beauty. Inspired by the wave of gruesome
femicides in her home state of Veracruz, the author transposes the
violence directed at women to the register of fable.

***  The King at the Edge of the World

By Arthur Phillips. $27.00. Random House.

Intrigue and espionage fuel this delectable novel set during the
twilight of the reign of Elizabeth I and featuring a Muslim Ottoman
physician who is enlisted in the machinations surrounding the choice
of the queen’s successor. 

***  Monogamy

By Sue Miller. $28.99. Harper/HarperCollins.


A gregarious bookstore owner dies suddenly, leaving his widow,
children and ex-wife to make sense of the messy and colorful life they
shared together. Sue Miller’s engrossing novel is infused with
generosity and the complicated kind of love readers will recognize
from real life.

***  Red Pill

By Hari Kunzru. $27.95. Knopf.

A fellowship at a study center in Germany turns sinister and sets a
writer on a possibly paranoid quest to expose a political evil he
believes is loose in the world. Kunzru’s wonderfully weird novel
traces a lineage from German Romanticism to National Socialism to the
alt-right, and is rich with insights on surveillance and power.


* non-fiction

** preferred (6)

***  Burning Down the House: Newt Gingrich, the Fall of a Speaker, and the Rise of the New Republican Party

By Julian E. Zelizer. $30.00. Penguin Press.

As Zelizer recounts, Gingrich brought a new slash-and-burn style to
Congress in the late 1980s that disrupted old ways and led to repeated
Republican successes. v

***  The Dead Are Arising: The Life of Malcolm X

By Les Payne and Tamara Payne. $35.00. Liveright.  

Thirty years in the making and encompassing hundreds of original
interviews, this magisterial biography of Malcolm X was completed by
Les Payne’s daughter after his death in 2018. Its strengths lie in its
finely shaded, penetrating portrait of the Black activist and thinker,
whose legacy continues to find fresh resonance today.

***  Deaths of Despair and the Future of Capitalism

By Anne Case and Angus Deaton. $27.95. Princeton University.

This highly important book examines the pain and despair among white
blue-collar workers and suggests that the hopelessness they are
experiencing may eventually extend to the entire American work force.

***  The Saddest Words: William Faulkner’s Civil War

By Michael Gorra. $29.95. 

Gorra’s complex and thought-provoking meditation on Faulkner is rich
in insight, making the case for the novelist’s literary achievement
and his historical value — as an unparalleled chronicler of slavery’s
aftermath, and its damage to America’s psyche.

***  The Splendid and the Vile: A Saga of Churchill, Family, and Defiance During the Blitz

By Erik Larson. $32.00. Crown.

Larson’s account of Winston Churchill’s leadership during the 12
turbulent months from May 1940 to May 1941, when Britain stood alone
and on the brink of defeat, is fresh, fast and deeply moving.

***  Until the End of Time: Mind, Matter, and Our Search for Meaning in an Evolving Universe

By Brian Greene. $30.00. Knopf.

Few humans share Greene’s mastery of both the latest cosmological
science and English prose. Here the best-selling physicist takes on
our deepest mysteries: consciousness, creativity and the end of time.


** routine (4)

***  A Pilgrimage to Eternity: From Canterbury to Rome in Search of a Faith

By Timothy Egan. $28.00. Viking.

Nonfiction.

In his ninth book, this self-described “lapsed but listening” Irish
Catholic travels 1,200 miles from Canterbury to Rome along the Via
Francigena and tries to decide what he believes. If this book doesn’t
settle the question, it will at least fortify faith in scrupulous
reporting and captivating storytelling.
***  A Dominant Character: The Radical Science and Restless Politics of J. B. S. Haldane

By Samanth Subramanian. $40.00. Norton.

Haldane, the British biologist and ardent communist who helped
synthesize Darwinian evolution with Mendelian genetics, was once as
famous as Einstein. Subramanian’s elegant biography doubles as a
timely allegory of the fraught relationship between science and
politics.

***  Shakespeare in a Divided America: What His Plays Tell Us About Our Past and Future

By James Shapiro. $27.00. Penguin Press.

Nonfiction.

Shapiro has long created Shakespeare treats for the common reader, but
this time he outdoes himself. From John Quincy Adams’s racist attacks
on “Othello” to the notorious Trump-as-Julius-Caesar Central Park
production in 2017, he reminds us how divided we’ve been since our
very beginnings, with the historical-tragical constantly muscling out
the pastoral-comical.

***  War: How Conflict Shaped Us
By Margaret MacMillan. $30.00. Random House.

Nonfiction.

This is a short book but a rich one with a profound theme. MacMillan
argues that war — fighting and killing — is so intimately bound up
with what it means to be human that viewing it as an aberration misses
the point. War has led to many of civilization’s great disasters but
also to many of civilization’s greatest achievements.

